# General settings
name: 'digress_align'      # Warning: 'debug' and 'test' are reserved name that have a special behavior
wandb: 'online'             # online | offline | disabled
gpus: 1                   # Multi-gpu is not implemented on this branch

resume: null            # If resume, path to ckpt file from outputs directory in main directory
test_only: null         # Use absolute path

check_val_every_n_epochs: 2
log_every_steps: 50
remove_log: False

