# Model settings
type: 'discrete_align'
transition: 'uniform'                          # uniform or marginal
model: 'graph_tf'
diffusion_steps: 50
diffusion_noise_schedule: 'cosine'              # 'cosine', 'polynomial_2'

extra_features: 'all'        # 'all', 'cycles', 'eigenvalues' or null

scalar_dim: 20
num_layers: 3
embed_dim: 128
cat: True 
lin: True
dropout: 0.0
