# Model settings
type: 'discrete_align'
transition: 'uniform'                          # uniform or matching
model: 'graph_tf'
diffusion_steps: 15
diffusion_noise_schedule: 'cosine'              # 'cosine', 'lin'
scalar_dim: 20 # rightnow it is a little bit problematic
num_visual: 8
dropout: 0.0
loss_type: 'ce' # 'hybrid', 'lvb_advance', or 'ce'
sample_mode: 'wr' # 'wor' or 'wr'
ce_weight: 1.
vb_weight: 0.0
use_argmax: False # True or False
metropolis: False
