defaults:
    - _self_
    - general : general_default_align
    - model : discrete_align
    - train : train_default
    - dataset : data_config

hydra:
    run:
        dir: ./outputs/${model.transition}_T${model.diffusion_steps}_${model.sample_mode}_ce${model.ce_weight}_vb${model.vb_weight}/${now:%Y-%m-%d_%H-%M-%S}
